service: interview-question-generator

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    GROQ_API_KEY: ${env:GROQ_API_KEY}
  httpApi:
    cors: true

functions:
  generateQuestions:
    handler: handler.generateQuestions
    timeout: 60
    events:
      - httpApi:
          path: /generate
          method: post

plugins:
  - serverless-offline